services:
  explorer:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    environment:
      K8S_NAMESPACE: default
      PORT: "8080"
      INSECURE_SKIP_TLS_VERIFY: "true"
    volumes:
      - ${HOME}/.kube/config:/kube/config:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
